services:
  postgres:
    image: postgres:16
    container_name: opr3-postgres
    environment:
      POSTGRES_DB: opr3
      POSTGRES_USER: opr3
      POSTGRES_PASSWORD: opr3
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: opr3-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@opr3.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  pgdata: {}
